### ISSUE TITLE
Axios not working 

### ISSUE THREAD

**Issue by srburton** [extism/js-pdk#13]
I'm trying to make a post request to a specific endpoint but it's not working.

![Screenshot_4](https://user-images.githubusercontent.com/15394508/222624631-1114eb75-90d0-471f-b32e-b370292369db.png)

![Screenshot_5](https://user-images.githubusercontent.com/15394508/222624757-0e195db1-d22b-4fe1-ada8-eaed7c60e2cd.png)

![Screenshot_6](https://user-images.githubusercontent.com/15394508/222624902-82ea7253-5908-45b9-b332-0cdbce184fdf.png)

**Comment by bhelx** [comment]
We don't yet support making http requests from this library yet. We still have some pieces from the runtime we are missing, but it is supported in our PDK. .e.g, here is how you'd do it in a rust plugin: https://extism.org/docs/write-a-plugin/rust-pdk#using-extism-built-in-http

My thinking was I'd expose it in the Javascript library and maybe use it to implement the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). Would that work for you? I'm not sure what axios uses under the hood but if it supports fetch then it will work.

Is this a blocker for you at the moment?

**Comment by srburton** [comment]
It doesn't block me, thinking here it's even good that he can't make a request. I'm just really testing the lib, by the way I really liked the proposal even though I have some limitations. :-)

**Comment by bhelx** [comment]
Cool thanks for testing it out! Feel free to post an issue anytime. This reminds me that in the meantime i need to put up a table of what we support now and what we are yet to support.

**Comment by bhelx** [comment]
This won't make axios work, but this will allow you to make HTTP requests from the plugin: https://github.com/extism/js-pdk/pull/14
